version: "3.8"

services:
  db:
    image: postgres:15
    container_name: los_db
    environment:
      POSTGRES_DB: los_db
      POSTGRES_USER: los_user
      POSTGRES_PASSWORD: los_password
    ports:
      - "5432:5432"
    volumes:
      - los_postgres_data:/var/lib/postgresql/data

volumes:
  los_postgres_data:
